// This file is auto-generated by: pnpm db:generate
// Run `supabase gen types typescript --local > src/types/supabase.ts` to regenerate
// Do not edit manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string;
          phone_number: string;
          date_of_birth: string | null;
          gender: "MALE" | "FEMALE" | "OTHER" | null;
          profile_picture_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["profiles"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
        Relationships: [];
      };
      clinics: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          address: string;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          phone_number: string | null;
          email: string | null;
          operating_hours: Record<string, unknown> | null;
          latitude: number | null;
          longitude: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["clinics"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["clinics"]["Insert"]>;
        Relationships: [];
      };
      clinic_staff: {
        Row: {
          id: string;
          user_id: string;
          clinic_id: string;
          role: "DOCTOR" | "RECEPTIONIST" | "ADMIN";
          full_name: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["clinic_staff"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["clinic_staff"]["Insert"]>;
        Relationships: [];
      };
      doctors: {
        Row: {
          id: string;
          specialization: string | null;
          qualification: string | null;
          consultation_duration_minutes: number;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["doctors"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["doctors"]["Insert"]>;
        Relationships: [];
      };
      doctor_schedules: {
        Row: {
          id: string;
          doctor_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["doctor_schedules"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["doctor_schedules"]["Insert"]>;
        Relationships: [];
      };
      time_slots: {
        Row: {
          id: string;
          doctor_id: string;
          slot_date: string;
          start_time: string;
          end_time: string;
          status: "AVAILABLE" | "BOOKED" | "BLOCKED" | "BREAK";
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["time_slots"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["time_slots"]["Insert"]>;
        Relationships: [];
      };
      appointments: {
        Row: {
          id: string;
          patient_id: string;
          doctor_id: string;
          clinic_id: string;
          time_slot_id: string;
          status: "PENDING" | "CONFIRMED" | "CHECKED_IN" | "COMPLETED" | "CANCELLED" | "NO_SHOW";
          appointment_date: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["appointments"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["appointments"]["Insert"]>;
        Relationships: [];
      };
      queues: {
        Row: {
          id: string;
          clinic_id: string;
          doctor_id: string;
          queue_date: string;
          is_active: boolean;
          current_number: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["queues"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["queues"]["Insert"]>;
        Relationships: [];
      };
      queue_entries: {
        Row: {
          id: string;
          queue_id: string;
          patient_id: string;
          appointment_id: string | null;
          queue_number: number;
          type: "APPOINTMENT" | "WALK_IN";
          priority: number;
          status: "WAITING" | "CALLED" | "IN_CONSULTATION" | "COMPLETED" | "SKIPPED" | "REMOVED";
          joined_at: string;
          called_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["queue_entries"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["queue_entries"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];

export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
